### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by BunnyRaizo** [till-f/MP3-Optimizer-for-Blue-Me#1] opened 2022-03-03 14:23 UTC
all my songs are grayed out and when I try to convert them the error on the title pops up
![Untitled](https://user-images.githubusercontent.com/60755135/156583552-754f552d-9aec-4a97-8ddb-7591124e9268.jpg)

**Comment by till-f** [comment] 2022-03-03 17:58
Hi, can you please send the corresponding mp3 file to thefish1@gmx.de? Then I could have a look at it. Please also tell me the version number (e.g. "1.1.0.0") and the settings (e.g. did you check "Rename Files" and "Quick Run")?

**Comment by BunnyRaizo** [comment] 2022-03-03 18:03
> Hi, can you please send the corresponding mp3 file to [thefish1@gmx.de](mailto:thefish1@gmx.de)? Then I could have a look at it. Please also tell me the version number (e.g. "1.1.0.0") and the settings (e.g. did you check "Rename Files" and "Quick Run")?

They are too many 😅
The version is the newest..
No I haven't tried that, I'll do that when I get home from work and let you know!
Thank you for the reply 🖤

**Comment by till-f** [comment] 2022-03-03 18:46
The problematic file would be enough, so you don't have to send all of them. Because it is working fine with thousands of files on my end it might be difficult to find the root cause without a problematic file.

Alternatively, try with a smaller number of files or different files (just to verify that it is not a general problem).

**Comment by BunnyRaizo** [comment] 2022-03-03 19:26
Okay,I'll send you a couple samples asap

**Comment by till-f** [comment] 2022-03-04 16:49
Hi, I could not access your shared files quickly (my Google account is not coupled with that email address). But it seems that [Lyra1337](https://github.com/till-f/MP3-Optimizer-for-Blue-Me/issues?q=is%3Apr+author%3ALyra1337) already found the problem (PR #2). Please try new version [1.1.1.0](https://github.com/till-f/MP3-Optimizer-for-Blue-Me/releases/tag/1.1.1.0). If it doesn't work I'll check your files again.

**Comment by BunnyRaizo** [comment] 2022-03-04 22:16
![image](https://user-images.githubusercontent.com/60755135/156849283-8062a55a-26af-4d4a-8e7b-e4ba59a597ec.png)
 
 Well,this version has this problem ..

**Comment by till-f** [comment] 2022-03-06 10:01
Ok, but this is a different issue. I've created issue #3 and will close this one.

Please provide some details what you did before the error popped up.

Meanwile, I'll add some logging and will handle such errors more gentle (not abort everything but just skip problematic files).

**Closed as completed** 2022-03-06 10:02 UTC
